### ISSUE TITLE
StickyHeader::disableCss() is not working inside Filament::serving

### ISSUE THREAD

**Issue by bernhardh** [awcodes/filament-sticky-header#15]
Hey! 

First of all, in the docs, there is `);`  missing:

```php
use FilamentStickyHeader\Facades\StickyHeader;

public function boot(): void
{
    Filament::serving(function () {
        StickyHeader::disableCss();
    });
}
```
instead of

```php
use FilamentStickyHeader\Facades\StickyHeader;

public function boot(): void
{
    Filament::serving(function () {
        StickyHeader::disableCss();
    }
}
```

And are you sure, that this is working? When calling `StickyHeader::disableCss()` inside the `serving` callback, it looks like it has no effect. Calling it directly, without the `Filament::serving` it works.

And why not doing the same for the JS? Then we could combine the js as well?

**Comment by awcodes** [comment]
Yea, it works. Not sure why it isn't working inside Filament::serving. It's a known bug. Will get to it as soon as possible. Also, when you disableCss() make sure you are adding the plugin styles into your theme css file.

**Comment by awcodes** [comment]
Looks like this is a lifecycle issue. I've updated the docs. You should call the StickyHeader facade in your register method so it's settings are available to Filament when it's booted.
