### ISSUE TITLE
Sticky header occurs even if it's not included in the panel provider plugins

### ISSUE THREAD

**Issue by grahammtbr** [awcodes/filament-sticky-header#27]
### Filament Version

v3

### Plugin Version

v2.0.4

### PHP Version

PHP 8.1

### Problem description

Minor thing, as I can just remove it from composer, but...

Like the title says, the plugin creates a sticky header even if it's commented out, or deleted from the panel provider plugins. Latest version of Filament.

```php
public function panel(Panel $panel): Panel
{
    return $panel
        ->plugins([
           // StickyHeaderPlugin::make(),
        ])
    ])
}
```

### Expected behavior

Not to have a sticky header if not included in ->plugins

### Steps to reproduce

In a filament project:
```
composer require awcodes/filament-sticky-header
```
Nothing more needed, just go to a long resource edit page and scroll down!

**Comment by grahammtbr** [comment]
Cheers, composer version is still on 2.0.4 :wink:

**Comment by awcodes** [comment]
Thanks. guess packagist didn't get the memo. showing as 2.0.5 now. :)
