### ISSUE TITLE
Bug In SPA Mode 

### ISSUE THREAD

**Issue by DeviJv** [awcodes/filament-sticky-header#29]
### Filament Version

v3

### Plugin Version

2

### PHP Version

8.2

### Problem description

not Sticky Header if SPA mode when change the pages 
i Should hot reload and it sticky again

[screen-capture.webm](https://github.com/awcodes/filament-sticky-header/assets/26791396/af9f07a2-4aae-4e7f-9a49-40ab7a77b04d)

### Expected behavior

because of SPA Mode?

### Steps to reproduce

added spa() in adminpanel and when pages navigate to view or edit page in spa mode sticky header not work but,
if i hot reload the page it working again

**Comment by awcodes** [comment]
I'm open to ideas on this, but I'm not sure it will work with SPA mode since the script requires a window onload event handler.

**Comment by DeviJv** [comment]
ok i thought this is a bug 

thx btw this is great plugin
