### ISSUE TITLE
Not working with `spa()` mode

### ISSUE THREAD

**Issue by bernhardh** [awcodes/filament-sticky-header#37]
### Filament Version

v3

### Plugin Version

v2.0.5

### PHP Version

8.2.25

### Problem description

When using the Filament `spa()` mode (https://filamentphp.com/docs/3.x/panels/configuration#spa-mode), the top bar isn't consistantly sticky anymore.

### Expected behavior

The header should be sticky

### Steps to reproduce

Just activate the SPA mode in your panel provider:

```php
public function panel(Panel $panel): Panel
{
    return $panel
        // ...
        ->spa();
}
```

And then test:

1. Load the page with /admin
2. Navigate to some resource index
3. Go to first resource to edit -> Scroll down -> Header is not sticky
4. Reload the page with CTRL+R -> scroll down -> now its sticky

**Comment by awcodes** [comment]
I'll see if I can figure something out. The problem is that the elements have to be there on page load for the JS to take effect and with SPA mode, they are injected after the script tries to initialize.

**Comment by bernhardh** [comment]
Thanks!
